import "~/styles/globals.css";

import "~/styles/animate.css";
import "~/styles/font-awesome.min.css";
import "~/styles/pnotify.custom.min.css";
import "~/styles/slick.css";

import "~/styles/scss/main.scss";

import { GeistSans } from "geist/font/sans";

import { TRPCReactProvider } from "~/trpc/react";
import AOSProvider from "~/app/_providers/AOSProvider";

export const metadata = {
  title: "Portfolio - Marcin Kalinowski",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <AOSProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </AOSProvider>
      </body>
    </html>
  );
}
