import { type PropsWithChildren } from "react";

import "~/styles/globals.css";
import "~/styles/animate.css";
import "~/styles/font-awesome.min.css";
import "~/styles/pnotify.custom.min.css";

import "~/styles/slick.css";

import "~/styles/scss/main.scss";

import { Roboto, Oswald } from "next/font/google";
import { TRPCReactProvider } from "~/trpc/react";
import AOSProvider from "~/app/_providers/AOSProvider";

export const metadata = {
  title: "Portfolio - Marcin Kalinowski",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const roboto = Roboto({
  weight: ["100", "300", "400", "500"],
  subsets: ["latin-ext"],
  variable: "--font-roboto",
});
const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`${roboto.variable} ${oswald.variable}`}>
      <body>
        <AOSProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </AOSProvider>
      </body>
    </html>
  );
}
